[package]
name = "linker"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
# BEGIN AUTO-PLUGINS
dummy = { path = "../plugins/core/dummy" }
profiler = { path = "../plugins/core/profiler" }
# END AUTO-PLUGINS
